class_name: XGBoostClassifierWrapper
save_name: XGBoostClassifier
hyperparams:
    objective: binary:logistic
    n_estimators: [1, 2, 3]
    max_depth: [1, 2, 3]
    learning_rate: 0.1
    eval_metric: auc
